// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { Nero$Type } from "./Nero";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Nero"]: Nero$Type;
    ["contracts/Nero.sol:Nero"]: Nero$Type;
  }
}
