// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { ERC721A$Type } from "./ERC721A";
import { ERC721A__IERC721Receiver$Type } from "./ERC721A__IERC721Receiver";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC721A"]: ERC721A$Type;
    ["ERC721A__IERC721Receiver"]: ERC721A__IERC721Receiver$Type;
    ["erc721a/contracts/ERC721A.sol:ERC721A"]: ERC721A$Type;
    ["erc721a/contracts/ERC721A.sol:ERC721A__IERC721Receiver"]: ERC721A__IERC721Receiver$Type;
  }
}
