// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IERC721A$Type } from "./IERC721A";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IERC721A"]: IERC721A$Type;
    ["erc721a/contracts/IERC721A.sol:IERC721A"]: IERC721A$Type;
  }
}
